### ISSUE TITLE
Actual distance

### ISSUE THREAD

**Issue by hetryn** [dpbenalcazar/irisDepth#2]
Hi,

How do I get back actual depth distance in real world using the predicted depth map produced? 

thks

**Comment by dpbenalcazar** [comment]
Thanks for the question. There are two answers.

1) You can use equations 4, 5 and 6 from the paper to do so. If you treat each pixel coordinate in the 256x256 input image as an individual point in the (u, v) coordinate system, then equations 4 and 5 help you transform those points into (x, y) coordinates in the real world units [mm], where H=W=256. Then, you can extrude those points in the z axis using the depth values from the depthmap by means of equation 6.  
![Prediction to real world coordinates](https://user-images.githubusercontent.com/61192501/138885437-30d085fa-3a97-41ae-a8e2-9e2049841569.png)

2) I implemented a function in Matlab that makes those calculations and stores the 3D model in stl format in millimeters. It is under: irisDepth/3D Iris in Matlab/Iris_3D_model_from_depthmap.m

I hope this was useful,
Daniel
