### ISSUE TITLE
Google Drive URL 404

### ISSUE THREAD

**Issue by muyouhang** [dpbenalcazar/irisDepth#3]
https://drive.google.com/drive/folders/1W6yxefISGz-kx6jJcNSFgD3-Ea9pbEZU?usp=sharing
https://drive.google.com/drive/folders/1o6uPcxTo7TefNoRWasr5BCI4RBftN5Xo?usp=sharing
https://drive.google.com/open?id=1IyLHCaVNPKhlF2B2iX-y_mnN3Ay62q7P
https://drive.google.com/drive/folders/1teohEBFo03j3kErZn1DBspypa32sOhve?usp=sharing

All the links are failed to visit,  could you share the new links?

**Comment by dpbenalcazar** [comment]
Sorry, those were Google Drive (GD) links associated with my account at Universidad de Chile. I just found out that a couple months ago the university decided to remove GD files of former students. I´m going to evaluate a better alternative to re-upload the files.

**Comment by muyouhang** [comment]
> Sorry, those were Google Drive (GD) links associated with my account at 智利大学. I just found out that a couple months ago the university decided to remove GD files of former students. I´m going to evaluate a better alternative to re-upload the files.

I am looking forward to the new download link,  thank you very much.

**Comment by muyouhang** [comment]
> Sorry, those were Google Drive (GD) links associated with my account at Universidad de Chile. I just found out that a couple months ago the university decided to remove GD files of former students. I´m going to evaluate a better alternative to re-upload the files.

I am looking forward to the new download link, thank you very much.

**Comment by dpbenalcazar** [comment]
I´ve just uploaded the weights and datasets to a new location. The new links are functional in the most recent update.

**Comment by muyouhang** [comment]
I'm already downloading these files, sincerely thanks again.
